### ISSUE TITLE
Python Version 2.7 or 3

### ISSUE THREAD

**Issue by adamisntdead** [conorcaseyc/Photopollution-Calculator-for-Munster#3]
Hello!

I noticed that this project is not supported by python3 or even python2.7, which might be worth doing

**Comment by conorcaseyc** [comment]
Currently, it only supports Python 2.7, however, a Python 3 version will be launched within a few days. To run the program, it is important that you run the Program.py file. Please also ensure you have the Python module, Pandas, installed. It can be downloaded with the Anaconda package. If you have any other problems, please contact me.

**Comment by conorcaseyc** [comment]
A version of our photopollution calculator is now available in Python 3. Simply run the file Program_3.py
